feat(infra): add commitlint in commit-msg hook

diff --git a/common/git-hooks/commit-msg b/common/git-hooks/commit-msg
--- a/common/git-hooks/commit-msg
+++ b/common/git-hooks/commit-msg
@@ -18,8 +18,18 @@
 
 # This example enforces that commit message should contain a minimum amount of
 # description text.
-if [ `cat $1 | wc -w` -lt 3 ]; then
-  echo ""
-  echo "Invalid commit message: The message must contain at least 3 words."
-	exit 1
+# if [ `cat $1 | wc -w` -lt 3 ]; then
+#   echo ""
+#   echo "Invalid commit message: The message must contain at least 3 words."
+# 	exit 1
+# fi
+
+# Skip commitlint if in rebase
+BRANCH_NAME=$(git branch | grep '*' | sed 's/* //')
+if [[ "X${BRANCH_NAME}" == "X(no branch"* ]]; then
+  exit
+else
+  node common/scripts/install-run-rush.js -q commitlint \
+    --config common/autoinstallers/infra/commitlint.config.cjs \
+    --edit "$1" || exit 1
 fi
